// The content of this file was generated by IBM Cloud
// No not modify it as it might get overridden

var IBMCloudEnv = require('ibm-cloud-env');
var serviceManager = require('./service-manager');
const db = require("../config/database");

IBMCloudEnv.init();

module.exports = function (app) {
    app.get('/companies/:id', (req, res) => {
        if (!req.params.id == "123456789") {
            return res.json({
                code: 500,
                message: 'Invalid request'
            });
        } else {

            const findData = "select company, rank, state_l, founded, industry, metro, website FROM `software-architecture-s4`.companies order by rank;";
            db.query(findData, (err, data) => {
                if (err) {
                    return res.json({
                        code: 400,
                        message: 'No details found'
                    });
                } else {
                    if (data.length > 0) {
                        return res.json({
                            code: 200,
                            status: 1,
                            message: data
                        });
                    } else {
                        return res.json({
                            code: 200,
                            status: 1,
                            message: 'No details found'
                        });
                    }
                }
            });
        }
    });
};