// The content of this file was generated by IBM Cloud
// No not modify it as it might get overridden

var IBMCloudEnv = require('ibm-cloud-env');
var serviceManager = require('./service-manager');
IBMCloudEnv.init();

const mongoose = require('mongoose');
//const Companies = mongoose.model('Companies', CompaniesSchema);;
const Companies = require('../models/companies');

// var jsonContent = JSON.parse(companiesDB);

module.exports = function (app) {
    app.get('/companies/list/:id', (req, res) => {
        console.log('Check all list');
        if (req.params.id !== "123456789") {
            return res.json({
                code: 200,
                message: 'Invalid request'
            });
        } else {
            // return res.send(companiesDB);
            console.log('Valid request to find list');
            Companies.find().limit(200),
                function (err, data) {
                    if (err) {
                        console.log('err found ', err);
                        return res.send({
                            code: 500,
                            message: 'Something went wrong. Try again!'
                        });
                    } else {
                        console.log('Found collection details ', data);
                        return res.send({
                            code: 200,
                            message: data
                        });
                    }
                }
        }
    });

    // Request https://companies-2018.mybluemix.net/companies/find?company=test1&state=test2&founded=2019
    app.post('/companies/find', (req, res) => {
        const company = req.body.company;
        const state = req.body.state;
        const founded = req.body.founded;

        console.log('company ', req.body.company);
        console.log('state ', req.body.state);
        console.log('founded ', req.body.founded);

        Companies.find({
                company: company,
                state: state,
                founded: founded
            }),
            function (err, data) {
                if (err) {
                    console.log('err found ', err);
                    return res.send({
                        code: 500,
                        message: 'Something went wrong. Try again!'
                    });
                } else {
                    console.log('Found collection details ', data);
                    return res.send(JSON.stringify(data));
                }
            }
    });
}